authService:
  host: "handshake-auth.sofine.my.id"
  replicas: 1
  image:
    repository: registry.sofine.my.id/handshake/auth-service
    tag: b43c5fd
  secretName: handshake-auth-service
  database:
    replicas: 1
    image:
      repository: postgres
      tag: alpine3.23
    secretName: handshake-auth-db
    storage:
      className: "do-block-storage-retain"
      accessModes:
        - ReadWriteOnce

productService:
  host: "handshake-product.sofine.my.id"
  replicas: 1
  image:
    repository: registry.sofine.my.id/handshake/product-service
    tag: b43c5fd
  secretName: handshake-product-service
  database:
    replicas: 1
    image:
      repository: postgres
      tag: alpine3.23
    secretName: handshake-product-db
    storage:
      className: "do-block-storage-retain"
      accessModes:
        - ReadWriteOnce

orderService:
  host: "handshake-order.sofine.my.id"
  replicas: 1
  image:
    repository: registry.sofine.my.id/handshake/order-service
    tag: b43c5fd
  secretName: handshake-order-service
  database:
    replicas: 1
    image:
      repository: postgres
      tag: alpine3.23
    secretName: handshake-order-db
    storage:
      className: "do-block-storage-retain"
      accessModes:
        - ReadWriteOnce
