apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "handshake.product" . }}
  labels: {{ include "handshake.product.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ template "handshake.product.host" . }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ template "handshake.product" . }}
                port:
                  number: {{ template "handshake.product.port" . }}
