apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "handshake.auth" . }}
  labels: {{ include "handshake.auth.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.authService.replicas }}
  selector:
    matchLabels: {{ include "handshake.auth.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "handshake.auth.labels" . | nindent 8 }}
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.authService.image.repository }}:{{ .Values.authService.image.tag }}
          ports:
            - containerPort: {{ template "handshake.auth.port" . }}
          envFrom:
            - secretRef:
                name: {{ .Values.authService.secretName }}
          livenessProbe:
            httpGet:
              path: /live
              port: {{ template "handshake.auth.port" . }}
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ template "handshake.auth.port" . }}
            initialDelaySeconds: 5
            periodSeconds: 5
